
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[226] =
    {   0,
        0,    0,    0,    0,    6,    6,   59,   57,   55,   56,
       56,   33,    2,   31,   57,   27,   37,   19,   35,   20,
       30,   57,   21,   53,   53,   13,   29,   18,   24,   52,
       28,   38,   14,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   25,   57,
       36,   12,   11,   11,   12,    6,    4,    3,    3,    5,
       58,   56,   32,    0,    1,    0,   17,   51,   54,    9,
        8,   54,   53,    0,    0,    0,   53,   26,   22,   23,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   51,   41,

       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   34,   11,   10,    6,    0,    3,    7,    0,
       54,    0,    0,   54,   53,   53,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   40,   52,   52,   52,
       43,   51,    0,   52,   52,   52,   52,   52,   52,   52,
       42,    0,   54,    0,   54,   45,   52,   52,   52,   52,
       52,   39,   52,   52,    0,   49,   52,   52,    0,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,    0,   52,   52,    0,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,    0,   52,    0,   52,

       16,   52,   46,   52,   52,   44,    0,   52,   50,   15,
       52,   52,    0,   52,    0,   52,    0,    0,   52,    0,
        0,   47,    0,   48,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    1,    9,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   20,   20,   20,   20,   20,   20,    1,   23,   24,
       25,   26,    1,    1,   27,   28,   28,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   31,
       30,   30,   30,   30,   30,   30,   30,   32,   30,   30,
       33,   34,   35,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   46,   53,   54,   55,   56,   57,   58,   59,
       60,   46,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    1,    1,    1,    1,    4,    4,    4,    5,
        5,    5,    1,    1,    1,    5,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[234] =
    {   0,
        0,    0,   61,   62,   68,   75,  373,  673,  673,  673,
      366,  312,   60,  673,  319,  673,  673,  673,  291,  673,
      283,   65,   75,   93,   78,  673,  267,  255,  251,  137,
      673,  673,  155,  173,  191,   52,   28,   53,   79,   39,
       94,   80,   67,   86,  109,  173,  110,  179,  673,  208,
      673,  673,  673,  257,  235,  213,  212,  673,  237,  673,
      199,  673,  673,   74,  673,  209,  673,  673,  216,  673,
      673,  246,  252,  263,    0,  275,  281,  673,  673,  673,
        0,  288,    0,    0,    0,   73,   98,  137,  145,  197,
      205,  155,  253,  273,  128,  235,  210,  277,  258,  272,

      280,  283,  288,  295,  296,  300,  301,  307,  291,  312,
      315,  308,  673,  673,  673,  205,  337,  673,  673,  356,
      362,  379,  385,  389,    0,  348,  364,  343,  372,  335,
      365,  385,  380,  379,  391,  397,  384,  390,  394,  398,
      405,  401,  202,  406,  412,  411,  419,  429,  418,  425,
      424,  467,  471,  475,  479,  428,  455,  452,  459,  458,
      462,  465,  466,  469,  194,  472,  475,  476,  162,  493,
      490,  481,  494,  484,  489,  497,  510,  501,  505,  511,
      516,  136,  515,  523,  137,  528,  522,  527,  533,  534,
      537,  545,  544,  548,  506,  151,  126,  554,  100,  553,

      557,  558,  561,  572,  565,    0,  103,  578,  673,  568,
      585,  571,   93,  579,  115,  590,   93,   83,  584,   79,
       60,  673,   46,  673,  673,  643,  648,  653,  655,  657,
      662,  667,   68
    } ;

static yyconst flex_int16_t yy_def[234] =
    {   0,
      225,    1,  226,  226,  227,  227,  225,  225,  225,  225,
      225,  225,  228,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  229,
      225,  225,  229,  230,  230,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,  225,  225,
      225,  225,  225,  225,  225,  231,  231,  225,  225,  225,
      232,  225,  225,  228,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  233,  233,  225,  225,  225,  225,
       33,   33,   33,   33,   33,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,  225,  225,  225,  231,  225,  225,  225,  225,
      225,  225,  225,  225,  233,   76,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,  225,   35,   35,   35,   35,   35,   35,   35,
       35,  225,  225,  225,  225,   35,   35,   35,   35,   35,
       35,   35,   35,   35,  225,   35,   35,   35,  225,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,  225,   35,   35,  225,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   33,  225,   35,  225,   35,

       35,   35,   35,   35,   35,   33,  225,   35,  225,   35,
       35,   35,  225,   35,  225,   35,  225,  225,   35,  225,
      225,  225,  225,  225,    0,  225,  225,  225,  225,  225,
      225,  225,  225
    } ;

static yyconst flex_int16_t yy_nxt[737] =
    {   0,
        8,    9,   10,    9,   11,    9,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   25,   26,   27,   28,   29,   30,   30,   30,   30,
       30,   30,   31,    8,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   34,   41,   34,   34,   34,   42,   34,
       43,   44,   45,   46,   47,   34,   48,   34,   34,   34,
       49,   50,   51,   53,   53,   54,   54,   65,   92,   57,
       58,  125,   59,   55,   55,   60,   57,   58,   86,   59,
       86,   65,   60,   69,   69,   69,   69,   70,   89,   99,
      224,   86,   71,   66,   72,   90,   77,   77,   77,   77,

       93,   61,   91,   86,   86,   86,   74,   66,   61,   72,
      223,   73,   73,   73,   73,   94,  103,   86,   74,   86,
      104,   74,  105,   86,   75,   86,   95,   96,  222,   97,
       86,   86,   86,   74,   98,  100,   86,  221,   86,   74,
      220,  218,  101,  102,   86,  106,   86,  217,  127,  107,
       86,   75,  213,  209,   76,   81,   81,   81,   81,   86,
       86,   86,   86,   82,   82,   82,   82,   82,   82,  111,
      207,  206,   83,   81,   81,   81,   81,  128,  135,  199,
       86,   85,   85,   85,   85,   85,   85,   86,  197,   86,
       83,   81,   81,   81,   81,   86,  132,   86,  129,   85,

       85,   85,   85,   85,   85,   86,  116,   86,   83,   81,
       81,   81,   81,  108,  185,  112,   64,   85,   85,   85,
       85,   85,   85,   86,  182,   86,   83,  109,  169,   86,
      110,   86,  116,  130,   69,   69,   69,   69,  117,  118,
      116,   87,   64,   88,  120,  117,  117,   86,  116,   86,
       64,  116,  115,  116,  131,   86,  120,   86,   64,  114,
       86,   64,  137,   64,  121,  121,  121,  121,   72,  113,
       73,   73,   73,   73,  122,   80,  123,  120,  123,   79,
       74,  124,  124,  124,  124,   86,  122,   86,  123,  136,
      123,   78,   74,  126,  126,  126,  126,   72,   68,   77,

       77,   77,   77,   86,   68,   86,  133,  122,   86,   74,
       86,  143,  139,   74,   82,   82,   82,   82,   82,   82,
      134,   74,   86,   86,   86,   86,  138,   86,   67,   86,
       86,  140,   86,   86,  144,   86,   63,  141,   86,  142,
       86,   86,   74,  148,  116,   86,   86,   86,   86,  145,
       86,   86,   86,   86,  147,  146,  149,   86,   86,   86,
      151,  225,   86,  225,   86,   86,  150,   86,   62,  152,
      116,  152,  225,  225,  153,  153,  153,  153,  116,  157,
      121,  121,  121,  121,  142,   86,  116,   86,  225,  116,
      122,  116,  154,   86,  154,   86,  225,  155,  155,  155,

      155,  225,  122,  124,  124,  124,  124,  124,  124,  124,
      124,  156,  142,  165,   86,   86,   86,   86,  158,  159,
      162,  160,   86,  122,   86,  161,  163,  164,  166,   86,
       86,   86,   86,  225,   86,   86,   86,   86,  225,  225,
       86,   86,   86,   86,  142,  168,   86,   86,  167,   86,
       86,   86,  170,   86,  171,   86,   86,   86,   86,  173,
      225,   86,   86,   86,   86,  142,  172,  174,   86,   86,
       86,   86,  177,  175,   86,   86,   86,   86,   86,   86,
       86,   86,  225,  225,  176,  153,  153,  153,  153,  153,
      153,  153,  153,  155,  155,  155,  155,  155,  155,  155,

      155,  142,   86,  178,   86,   86,  142,   86,   86,   86,
       86,   86,   86,  179,  142,   86,   86,   86,   86,   86,
      180,   86,   86,  181,   86,   86,   86,  183,  184,  186,
      142,   86,  188,  187,  189,  191,   86,  196,  190,   86,
       86,   86,   86,   86,   86,   86,   86,   86,  192,   86,
      193,   86,  194,   86,  195,   86,   86,   86,  205,  225,
       86,   86,   86,   86,  198,   86,   86,   86,   86,  142,
      200,  201,   86,   86,   86,   86,  203,   86,   86,   86,
       86,  142,  202,   86,   86,   86,   86,   86,  142,   86,
      208,  142,  225,  210,   86,   86,   86,   86,   86,  204,

       86,  215,  142,   86,   86,   86,   86,   86,   86,   86,
       86,   86,  142,   86,  211,  212,  214,   86,   86,  142,
       86,   86,   86,   86,   86,  225,  216,  142,   86,   86,
       86,   86,  219,  225,   86,   86,   86,   86,  225,  225,
       86,  225,   86,   52,   52,   52,   52,   52,   56,   56,
       56,   56,   56,   64,  225,   64,   64,   64,   84,   84,
       86,   86,  116,  225,  225,  116,  116,  119,  119,  119,
      119,  119,    7,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,

      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225
    } ;

static yyconst flex_int16_t yy_chk[737] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    3,    4,   13,   37,    5,
        5,  233,    5,    3,    4,    5,    6,    6,   37,    6,
       37,   64,    6,   22,   22,   22,   22,   23,   36,   40,
      223,   40,   23,   13,   25,   36,   25,   25,   25,   25,

       38,    5,   36,   38,   36,   38,   25,   64,    6,   24,
      221,   24,   24,   24,   24,   39,   42,   43,   25,   43,
       43,   24,   44,   86,   24,   86,   39,   39,  220,   39,
       42,   39,   42,   24,   39,   41,   44,  218,   44,   25,
      217,  215,   41,   41,   41,   45,   41,  213,   87,   45,
       87,   24,  207,  199,   24,   30,   30,   30,   30,   45,
       47,   45,   47,   30,   30,   30,   30,   30,   30,   47,
      197,  196,   30,   33,   33,   33,   33,   88,   95,  185,
       95,   33,   33,   33,   33,   33,   33,   88,  182,   88,
       33,   34,   34,   34,   34,   89,   92,   89,   89,   34,

       34,   34,   34,   34,   34,   92,   61,   92,   34,   35,
       35,   35,   35,   46,  169,   48,   66,   35,   35,   35,
       35,   35,   35,   46,  165,   46,   35,   46,  143,   48,
       46,   48,   61,   90,   69,   69,   69,   69,  116,   59,
       61,   35,   66,   35,   69,   57,   56,   90,   61,   90,
       66,   61,   55,   61,   91,   91,   69,   91,   66,   54,
       97,   66,   97,   66,   72,   72,   72,   72,   73,   50,
       73,   73,   73,   73,   72,   29,   74,   69,   74,   28,
       73,   74,   74,   74,   74,   96,   72,   96,   76,   96,
       76,   27,   73,   76,   76,   76,   76,   77,   21,   77,

       77,   77,   77,   93,   19,   93,   93,   72,   99,   77,
       99,  104,   99,   73,   82,   82,   82,   82,   82,   82,
       94,   77,  100,   94,  100,   94,   98,   98,   15,   98,
      101,  101,  101,  102,  105,  102,   12,  102,  103,  103,
      103,  109,   77,  109,  117,  104,  105,  104,  105,  106,
      106,  107,  106,  107,  108,  107,  110,  108,  112,  108,
      112,  126,  110,  126,  110,  111,  111,  111,   11,  120,
      117,  120,    7,    0,  120,  120,  120,  120,  117,  128,
      121,  121,  121,  121,  130,  130,  117,  130,    0,  117,
      121,  117,  122,  128,  122,  128,    0,  122,  122,  122,

      122,    0,  121,  123,  123,  123,  123,  124,  124,  124,
      124,  127,  129,  136,  127,  131,  127,  131,  131,  131,
      133,  132,  129,  121,  129,  132,  134,  135,  138,  134,
      133,  134,  133,    0,  137,  132,  137,  132,    0,    0,
      138,  135,  138,  135,  139,  141,  139,  136,  140,  136,
      140,  142,  144,  142,  145,  141,  144,  141,  144,  147,
        0,  146,  145,  146,  145,  150,  146,  148,  149,  147,
      149,  147,  149,  148,  151,  150,  151,  150,  156,  148,
      156,  148,    0,    0,  148,  152,  152,  152,  152,  153,
      153,  153,  153,  154,  154,  154,  154,  155,  155,  155,

      155,  157,  158,  159,  158,  157,  158,  157,  160,  159,
      160,  159,  161,  160,  161,  162,  163,  162,  163,  164,
      163,  164,  166,  164,  166,  167,  168,  167,  168,  170,
      171,  172,  173,  172,  174,  176,  174,  181,  175,  175,
      171,  175,  171,  170,  173,  170,  173,  176,  177,  176,
      178,  178,  179,  178,  180,  179,  195,  179,  195,    0,
      177,  180,  177,  180,  184,  183,  181,  183,  181,  183,
      186,  187,  187,  184,  187,  184,  190,  188,  186,  188,
      186,  188,  189,  189,  190,  189,  190,  191,  192,  191,
      198,  191,    0,  200,  193,  192,  193,  192,  194,  193,

      194,  211,  194,  200,  198,  200,  198,  201,  202,  201,
      202,  203,  204,  203,  202,  205,  208,  205,  210,  214,
      210,  212,  204,  212,  204,    0,  212,  219,  208,  214,
      208,  214,  216,    0,  219,  211,  219,  211,    0,    0,
      216,    0,  216,  226,  226,  226,  226,  226,  227,  227,
      227,  227,  227,  228,    0,  228,  228,  228,  229,  229,
      230,  230,  231,    0,    0,  231,  231,  232,  232,  232,
      232,  232,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,

      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gocompiler.l"
#line 2 "gocompiler.l"
    #include "y.tab.h"
    #include <stdio.h>
    #include <string.h>
    #include "semantics.h"
                                                                                                       

    int lines_num=1;
    int cols_num=1;
    int comment_type=0;
    int show_res=0;
    int string_error=0;
    int flag_yacc_error=0;
    int semicolon = 0;
    int bracket_line = 0;
    int bracket_column = 0;
    int bracket_close = 0;
    int one_time = 0;
    char* buffer;
    extern int yydebug;
    extern node* root;
    struct Pos{
        int col;
        int line;
    };
    
    struct Pos comment_pos;
    struct Pos string_pos;
    struct Pos illegal_pos;


#line 721 "lex.yy.c"

#define INITIAL 0
#define Comment 1
#define String 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 48 "gocompiler.l"


#line 908 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 226 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 673 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "gocompiler.l"
{cols_num+=yyleng;bracket_column=cols_num;bracket_line=lines_num;semicolon=1;if(show_res==1) printf("STRLIT(%s)\n",yytext);else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng);return STRLIT;}}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "gocompiler.l"
{string_pos.line=lines_num;string_pos.col=cols_num;cols_num+=yyleng;BEGIN String;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 52 "gocompiler.l"
{printf("Line %d, column %d: unterminated string literal\n",string_pos.line,string_pos.col);lines_num++;cols_num=1;BEGIN 0;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "gocompiler.l"
{cols_num+=yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "gocompiler.l"
{BEGIN 0;if(show_res==1 && string_error==0)printf("STRLIT(%s)\n",buffer);cols_num+=yyleng;string_error=0;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "gocompiler.l"
{buffer=yytext;cols_num+=yyleng;}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 56 "gocompiler.l"
{printf("Line %d, column %d: invalid escape sequence (%s)\n",lines_num,cols_num,yytext);cols_num+=yyleng;string_error=1;}
	YY_BREAK
case YY_STATE_EOF(String):
#line 57 "gocompiler.l"
{printf("Line %d, column %d: unterminated string literal\n",string_pos.line,string_pos.col);yyterminate();}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "gocompiler.l"
{comment_type=2;BEGIN Comment;cols_num+=yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "gocompiler.l"
{comment_type=1;BEGIN Comment;comment_pos.col=cols_num;comment_pos.line=lines_num;cols_num+=yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "gocompiler.l"
{if(comment_type==1){comment_type=0;BEGIN 0;}cols_num+=yyleng;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 63 "gocompiler.l"
{if(comment_type==2){comment_type=0;BEGIN 0;};lines_num++;cols_num=1;}
	YY_BREAK
case YY_STATE_EOF(Comment):
#line 64 "gocompiler.l"
{if(comment_type==1)	printf("Line %d, column %d: unterminated comment\n",comment_pos.line,comment_pos.col);yyterminate();}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "gocompiler.l"
{cols_num+=yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "gocompiler.l"
{cols_num+=yyleng;bracket_column=cols_num;bracket_line=lines_num;semicolon=0;if(show_res==1) printf("SEMICOLON\n");else{ yylval.token = new_token(yytext, lines_num, cols_num-yyleng);return SEMICOLON;}}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("BLANKID\n");else{ yylval.token = new_token(yytext, lines_num, cols_num-yyleng);return BLANKID;}}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("PACKAGE\n");else{ yylval.token = new_token(yytext, lines_num, cols_num-yyleng);return PACKAGE;}}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "gocompiler.l"
{cols_num+=yyleng;semicolon=1;if(show_res==1) printf("RETURN\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return RETURN;}}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("AND\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return AND;}}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("ASSIGN\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return ASSIGN;}}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("STAR\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return STAR;}}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("COMMA\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return COMMA;}}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("DIV\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return DIV;}}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("EQ\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return EQ;}}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("GE\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return GE;}}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("GT\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return GT;}}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "gocompiler.l"
{cols_num+=yyleng;bracket_column=cols_num;bracket_line=lines_num;bracket_close++;semicolon=0;if(show_res==1) printf("LBRACE\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return LBRACE;}}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("LE\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return LE;}}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 83 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("LPAR\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return LPAR;}}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 84 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("LSQ\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return LSQ;}}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 85 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("LT\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return LT;}}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 86 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("MINUS\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return MINUS;}}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 87 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("MOD\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return MOD;}}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 88 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("NE\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return NE;}}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 89 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("NOT\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return NOT;}}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 90 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("OR\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return OR;}}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 91 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("PLUS\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return PLUS;}}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 92 "gocompiler.l"
{cols_num+=yyleng;bracket_column=cols_num;bracket_line=lines_num;bracket_close--;semicolon=1;if(show_res==1) printf("RBRACE\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return RBRACE;}}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 93 "gocompiler.l"
{cols_num+=yyleng;semicolon=1;if(show_res==1) printf("RPAR\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return RPAR;}}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "gocompiler.l"
{cols_num+=yyleng;semicolon=1;if(show_res==1) printf("RSQ\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return RSQ;}}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("ELSE\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return ELSE;}}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 96 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("FOR\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return FOR;}}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 97 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("IF\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return IF;}}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("VAR\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return VAR;}}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("INT\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return INT;}}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("FLOAT32\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return FLOAT32;}}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 101 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("BOOL\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return BOOL;}}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 102 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("STRING\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return STRING;}}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 103 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("PRINT\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return PRINT;}}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 104 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("PARSEINT\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return PARSEINT;}}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 105 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("FUNC\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return FUNC;}}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 106 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("CMDARGS\n");else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng); return CMDARGS;}}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 107 "gocompiler.l"
{cols_num+=yyleng;semicolon=0;if(show_res==1) printf("RESERVED(%s)\n",yytext);else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng);return RESERVED;}}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 108 "gocompiler.l"
{cols_num+=yyleng;bracket_column=cols_num;bracket_line=lines_num;semicolon=1;if(show_res==1) printf("ID(%s)\n",yytext);else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng);return ID;}}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 109 "gocompiler.l"
{cols_num+=yyleng;bracket_column=cols_num;bracket_line=lines_num;semicolon=1;if(show_res==1) printf("INTLIT(%s)\n",yytext);else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng);return INTLIT;}}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 110 "gocompiler.l"
{cols_num+=yyleng;bracket_column=cols_num;bracket_line=lines_num;semicolon=1;if(show_res==1) printf("REALLIT(%s)\n",yytext);else{yylval.token = new_token(yytext, lines_num, cols_num-yyleng);return REALLIT;}}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 111 "gocompiler.l"
{cols_num++;}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 112 "gocompiler.l"
{lines_num++;cols_num=1;if(semicolon==1){if(show_res==1){printf("SEMICOLON\n");semicolon=0;}else{semicolon=0;yylval.token = new_token(yytext, lines_num, cols_num-yyleng);return SEMICOLON;}}}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 113 "gocompiler.l"
{one_time=1;cols_num++;if(semicolon==1){if(show_res==1){printf("SEMICOLON\n");}else{semicolon=0;return SEMICOLON;}}yyterminate();}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "gocompiler.l"
{printf("Line %d, column %d: illegal character (%s)\n",lines_num,cols_num,yytext);cols_num+=yyleng;semicolon=0;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 116 "gocompiler.l"
ECHO;
	YY_BREAK
#line 1297 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 226 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 226 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 225);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 116 "gocompiler.l"


int main(int argc, char** argv){
    //yydebug=1;
    node* no;	
    if(argc>1){
        if(strcmp(argv[1],"-l")==0){
            show_res=1;
            yylex();
        }
        else if(strcmp(argv[1],"-t")==0){
            show_res = 0;
            yyparse();
            if(flag_yacc_error==0){
                print_tree(root,0);
                free_tree(root);
            }
        }
        else if(strcmp(argv[1],"-s")==0){
            show_res = 0;      
            yyparse();
            if(flag_yacc_error==0){
                no = check_program(root);
                print_symbol_table(ST);
		        printf("\n");
                print_anoted_tree(root,0);
                free_tree(root);
            }
        }
    }
    else{
        show_res = 0;
        yyparse();
        if(flag_yacc_error==0){
            no = check_program(root);
        }
    }
    return 0;
}

int yywrap(){
	return 1;
}

