
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[369] =
    {   0,
        0,    0,    0,    0,    0,    0,   66,   64,   61,   63,
       63,   62,   18,   54,   45,   16,   64,   12,   22,    4,
       20,    5,   15,   64,    6,   46,   46,   24,   14,    3,
        9,   45,   45,   45,   13,   23,   28,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   10,   64,   21,   53,   52,   52,
       53,   60,   58,   58,   55,   60,   63,   17,    0,   48,
        0,   45,   45,   45,   45,    2,   44,   25,   47,    0,
       50,   49,   47,    0,    0,    0,   46,    0,   26,   11,
        7,    8,   27,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   44,   45,   45,   45,
       45,   45,   45,   45,   45,   34,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   19,   52,   51,   58,   59,
       57,   57,   56,   45,   45,   45,   47,    0,    0,    0,
       47,    0,    0,   47,    0,   46,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   44,   45,   45,
       45,   35,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   57,    0,   47,   47,    0,   47,    0,
        0,    0,   47,   47,    0,   46,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   33,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,    1,   42,   45,   45,   47,    0,    0,    0,
       47,   47,   47,    0,   47,   45,   45,   45,   45,   45,
       45,   30,   45,   45,   45,   45,   44,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   44,   45,   45,   43,   47,    0,   47,    0,   47,

       45,   41,   44,   45,   45,   45,   45,   32,   45,   45,
       45,   45,   45,   45,   45,   45,   38,   39,   40,   45,
       45,   45,   45,   31,   47,   44,    0,   45,   29,   45,
       45,   45,   45,   45,   45,   45,   45,   45,    0,    0,
       45,   45,   45,   45,   45,   45,    0,    0,   45,   45,
       45,    0,    0,   45,    0,    0,   45,    0,    0,    0,
        0,    0,    0,    0,    0,   37,   36,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[375] =
    {   0,
        0,    0,   60,   61,   64,   65,  587,  588,  588,  588,
      583,  588,  561,   63,   71,  588,  573,  588,  588,  588,
      568,  588,   59,   57,   67,   86,   90,  588,   59,  558,
       63,  106,  533,   32,  588,  588,  588,   57,   63,   95,
       40,   90,   96,  531,    0,  103,  530,  113,  111,  539,
      115,   77,  528,  534,  588,  514,  588,  588,  588,  571,
      554,  588,  588,  569,  588,  150,  588,  588,  141,  588,
      146,    0,  184,    0,    0,  588,  588,  588,  168,  532,
      588,  588,  139,  188,  159,  162,  196,  199,  588,  588,
      588,  588,  588,  517,  518,  516,  515,  514,  516,  525,

      510,   49,  527,  526,  512,  519,  504,  505,  502,  502,
      508,  505,  503,  500,  497,    0,  499,   70,  500,  494,
      490,  499,  507,  121,  507,  489,  492,  140,  490,  496,
      490,  141,  186,  182,  494,  588,  588,  588,  588,  588,
      588,  533,  588,  222,    0,    0,  218,  238,  226,  487,
      241,  249,  216,  251,  256,  266,  495,  490,  479,  478,
      491,  483,  493,  488,  487,  488,  473,  471,  226,  487,
      485,  481,  472,  479,  465,  481,  480,    0,  465,  180,
      460,  473,  470,  467,  463,  463,  452,  453,  459,  450,
      452,  449,  458,  461,  446,  461,  445,  447,  447,  455,

      455,  457,  445,  588,  261,  268,  276,  449,  286,  297,
      288,  271,  303,  306,  308,  312,  448,  440,  448,  435,
      434,  445,  438,  440,  429,  427,  436,  424,  431,    0,
      428,  436,  428,  420,  433,  420,  435,  418,  413,  432,
      431,  426,  421,  412,  409,  418,  423,  408,  421,  415,
      400,  403,    0,    0,  401,  414,  314,  323,  399,  278,
      329,  332,  334,  340,  344,  412,  409,  402,  413,  394,
      411,    0,  397,  398,  404,  404,  395,  393,  386,  390,
      397,  397,  394,  381,  396,  395,  383,  393,  376,  386,
      376,  374,  382,  381,    0,  349,  381,  352,  355,  359,

      371,    0,  403,  383,  371,  364,  364,    0,  364,  357,
      375,  376,  377,  372,  371,  356,    0,    0,    0,  368,
      354,  355,  346,  588,  361,  373,  341,  335,    0,  348,
      337,  345,  340,  328,  312,  310,  308,  308,  295,  287,
      285,  287,  292,  283,  276,  263,  276,  251,  249,  254,
      214,  216,  247,  224,  202,  191,  196,  193,  173,  172,
      144,  137,  115,  108,  103,  588,  588,  588,  395,  398,
      401,  115,  404,  113
    } ;

static const flex_int16_t yy_def[375] =
    {   0,
      368,    1,  369,  369,  370,  370,  368,  368,  368,  368,
      368,  368,  368,  371,  372,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  372,   32,   32,  368,  368,  368,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  373,  368,  368,  371,  368,
      368,   32,  374,   32,   32,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,  368,  368,  368,  368,  368,
      368,  368,  368,  374,  144,  144,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   32,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,  368,  368,  368,  368,
      368,  368,  368,  368,  368,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,  368,  368,  368,  368,  368,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,  368,  368,   32,  368,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,  368,  368,
       32,   32,   32,   32,   32,   32,  368,  368,   32,   32,
       32,  368,  368,   32,  368,  368,   32,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,    0,  368,  368,
      368,  368,  368,  368
    } ;

static const flex_int16_t yy_nxt[651] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   32,   33,   34,   35,
        8,   36,   37,   15,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   45,   45,   47,   45,   48,   45,   49,
       50,   51,   52,   45,   53,   54,   45,   45,   45,   55,
       56,   57,   59,   59,   60,   60,   63,   63,   64,   64,
       70,   65,   65,   61,   61,   77,   79,   79,  106,   72,
       81,   89,   90,   78,   95,   82,   92,   93,  107,   96,
       73,   73,   97,   71,   66,   66,   74,   74,   74,   74,

      165,  166,   80,   83,   72,   84,   84,   83,   98,   87,
       87,   99,   85,  100,   72,  146,   85,   75,  132,   86,
      101,  181,  182,   88,   85,   73,   73,  133,   85,  102,
      111,   74,   74,   74,   74,  108,  103,  109,  112,   72,
      104,  113,  116,  105,  114,  123,  110,  120,   70,  117,
      118,  121,  141,   69,  142,  367,  127,  143,  151,  151,
      366,  124,  365,  187,  125,  152,  122,  128,  129,  188,
      130,   71,  131,  153,  192,  153,   69,  152,  154,  154,
      143,  155,  155,  197,  364,   69,  363,  147,  147,  143,
      193,  198,  144,   69,  148,   86,   69,  143,   69,  362,

      143,  149,  143,   73,   73,   83,  148,   84,   84,  145,
      145,  145,  145,   83,   85,   87,   87,  144,  156,  156,
      199,   86,   85,  361,  201,  235,   85,  202,  236,   88,
      144,  360,   88,  178,   85,  154,  154,  147,  147,  200,
      359,   73,   73,  178,  148,  207,  207,  145,  145,  145,
      145,  149,  205,  358,  205,  144,  148,  206,  206,  149,
      209,  209,  357,  212,  356,  212,  355,  210,  213,  213,
      214,  214,  354,   83,  211,  155,  155,  226,  227,  210,
      206,  206,   85,   83,  215,  216,  216,  257,  257,   86,
      213,  213,   85,  178,   85,  207,  207,  261,  261,   88,

      178,  258,  148,  353,   85,  209,  209,  262,  262,  149,
      352,  260,  210,  260,  148,  178,  261,  261,  351,  211,
      178,  211,  263,  263,  210,  214,  214,  265,  265,   83,
      178,  216,  216,  257,  257,  350,  264,  349,   85,  215,
      348,  215,  296,  296,  347,   88,  178,  258,  298,  298,
       85,  262,  262,  263,  263,  346,  258,  345,  210,  300,
      300,  178,  299,  265,  265,  211,  344,  264,  296,  296,
      210,  298,  298,  264,  325,  325,  343,  215,  300,  300,
      325,  325,  258,  342,  341,  299,  178,  178,  299,  340,
      339,  338,  264,  337,  299,   58,   58,   58,   62,   62,

       62,   69,  336,   69,  140,  140,  140,  335,  334,  178,
      178,  333,  332,  331,  178,  178,  178,  330,  329,  328,
      327,  326,  324,  323,  322,  178,  321,  178,  320,  319,
      318,  317,  316,  315,  314,  178,  313,  312,  178,  311,
      310,  309,  308,  307,  306,  305,  178,  304,  303,  302,
      301,  297,  295,  294,  293,  292,  291,  290,  178,  289,
      288,  178,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  178,  277,  253,  276,  275,  274,  273,  178,
      272,  178,  178,  271,  270,  269,  268,  267,  266,  259,
      256,  255,  254,  253,  252,  251,  178,  250,  249,  248,

      247,  246,  245,  244,  243,  242,  241,  240,  178,  239,
      178,  238,  237,  178,  234,  233,  232,  231,  178,  230,
      229,  228,  225,  178,  224,  178,  178,  223,  222,  221,
      220,  219,  218,  217,  208,  204,  203,  196,  195,  194,
      191,  190,  189,  186,  185,  178,  184,  183,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  164,  163,  162,  161,  160,  159,  158,  157,
      150,  139,  138,  137,  136,  135,  134,  126,  119,  115,
       94,   91,   77,   76,   68,   67,  368,    7,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368
    } ;

static const flex_int16_t yy_chk[651] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,    5,    6,    5,    6,
       14,    5,    6,    3,    4,   23,   24,   24,   41,   15,
       25,   29,   29,   23,   34,   25,   31,   31,   41,   34,
       15,   15,   38,   14,    5,    6,   15,   15,   15,   15,

      102,  102,   24,   26,   15,   26,   26,   27,   38,   27,
       27,   39,   26,   39,   32,  374,   27,  372,   52,   26,
       39,  118,  118,   27,   26,   32,   32,   52,   27,   40,
       43,   32,   32,   32,   32,   42,   40,   42,   43,   32,
       40,   43,   46,   40,   43,   49,   42,   48,   69,   46,
       46,   48,   66,   71,   66,  365,   51,   66,   83,   83,
      364,   49,  363,  124,   49,   83,   48,   51,   51,  124,
       51,   69,   51,   85,  128,   85,   71,   83,   85,   85,
       66,   86,   86,  132,  362,   71,  361,   79,   79,   66,
      128,  132,   73,   71,   79,   86,   71,   66,   71,  360,

       66,   79,   66,   73,   73,   84,   79,   84,   84,   73,
       73,   73,   73,   87,   84,   87,   87,   73,   88,   88,
      133,   84,   87,  359,  134,  180,   84,  134,  180,   87,
      144,  358,   88,  357,   87,  153,  153,  147,  147,  133,
      356,  144,  144,  133,  147,  149,  149,  144,  144,  144,
      144,  147,  148,  355,  148,  144,  147,  148,  148,  149,
      151,  151,  354,  152,  353,  152,  352,  151,  152,  152,
      154,  154,  351,  155,  151,  155,  155,  169,  169,  151,
      205,  205,  155,  156,  154,  156,  156,  206,  206,  155,
      212,  212,  156,  350,  155,  207,  207,  260,  260,  156,

      349,  206,  207,  348,  156,  209,  209,  211,  211,  207,
      347,  210,  209,  210,  207,  346,  210,  210,  345,  209,
      344,  211,  213,  213,  209,  214,  214,  215,  215,  216,
      343,  216,  216,  257,  257,  342,  213,  341,  216,  214,
      340,  215,  258,  258,  339,  216,  338,  257,  261,  261,
      216,  262,  262,  263,  263,  337,  258,  336,  262,  264,
      264,  335,  261,  265,  265,  262,  334,  263,  296,  296,
      262,  298,  298,  264,  299,  299,  333,  265,  300,  300,
      325,  325,  296,  332,  331,  298,  330,  328,  299,  327,
      326,  323,  300,  322,  325,  369,  369,  369,  370,  370,

      370,  371,  321,  371,  373,  373,  373,  320,  316,  315,
      314,  313,  312,  311,  310,  309,  307,  306,  305,  304,
      303,  301,  297,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  271,  270,  269,  268,  267,
      266,  259,  256,  255,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  208,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,

      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  179,  177,  176,  175,  174,  173,  172,
      171,  170,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  150,  142,  135,  131,  130,  129,
      127,  126,  125,  123,  122,  121,  120,  119,  117,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  101,  100,   99,   98,   97,   96,   95,   94,
       80,   64,   61,   60,   56,   54,   53,   50,   47,   44,
       33,   30,   21,   17,   13,   11,    7,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
#include "y.tab.h"
#include "node.h"
//2014230130 Ricardo Sintra Tavares

int multiLineComment = 0;
int line = 1;
int column = 1;
int printTokens = 0;

struct Position {
        int column;
        int line;
    };
struct Position commentTracker;
struct Position stringTracker;

extern Node* tree;
extern int syntaxError;
#line 725 "lex.yy.c"

#line 727 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRINGSTATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "jucompiler.l"


#line 949 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 369 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 588 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "jucompiler.l"
{if(printTokens == 1) {printf("BOOLLIT(%s)\n", yytext);} column += yyleng; if(printTokens == 0){ yylval.string = strdup(yytext); return BOOLLIT;}}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "jucompiler.l"
{if(printTokens == 1) {printf("AND\n");} column += yyleng; if(printTokens == 0){return AND;}}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "jucompiler.l"
{if(printTokens == 1) {printf("ASSIGN\n");} column += yyleng; if(printTokens == 0){return ASSIGN;}}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "jucompiler.l"
{if(printTokens == 1) {printf("STAR\n");} column += yyleng; if(printTokens == 0){return STAR;}}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{if(printTokens == 1) {printf("COMMA\n");} column += yyleng; if(printTokens == 0){return COMMA;}}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "jucompiler.l"
{if(printTokens == 1) {printf("DIV\n");} column += yyleng; if(printTokens == 0){return DIV;}}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{if(printTokens == 1) {printf("EQ\n");} column += yyleng; if(printTokens == 0){return EQ;}}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{if(printTokens == 1) {printf("GE\n");} column += yyleng; if(printTokens == 0){return GE;}}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{if(printTokens == 1) {printf("GT\n");} column += yyleng; if(printTokens == 0){return GT;}}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{if(printTokens == 1) {printf("LBRACE\n");} column += yyleng; if(printTokens == 0){return LBRACE;}}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{if(printTokens == 1) {printf("LE\n");} column += yyleng; if(printTokens == 0){return LE;}}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{if(printTokens == 1) {printf("LPAR\n");} column += yyleng; if(printTokens == 0){return LPAR;}}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{if(printTokens == 1) {printf("LSQ\n");} column += yyleng; if(printTokens == 0){return LSQ;}}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{if(printTokens == 1) {printf("LT\n");} column += yyleng; if(printTokens == 0){return LT;}}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{if(printTokens == 1) {printf("MINUS\n");} column += yyleng; if(printTokens == 0){return MINUS;}}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{if(printTokens == 1) {printf("MOD\n");} column += yyleng; if(printTokens == 0){return MOD;}}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{if(printTokens == 1) {printf("NE\n");} column += yyleng; if(printTokens == 0){return NE;}}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{if(printTokens == 1) {printf("NOT\n");} column += yyleng; if(printTokens == 0){return NOT;}}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "jucompiler.l"
{if(printTokens == 1) {printf("OR\n");} column += yyleng; if(printTokens == 0){return OR;}}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{if(printTokens == 1) {printf("PLUS\n");} column += yyleng; if(printTokens == 0){return PLUS;}}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "jucompiler.l"
{if(printTokens == 1) {printf("RBRACE\n");} column += yyleng; if(printTokens == 0){return RBRACE;}}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{if(printTokens == 1) {printf("RPAR\n");} column += yyleng; if(printTokens == 0){return RPAR;}}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "jucompiler.l"
{if(printTokens == 1) {printf("RSQ\n");} column += yyleng; if(printTokens == 0){return RSQ;}}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{if(printTokens == 1) {printf("SEMICOLON\n");} column += yyleng; if(printTokens == 0){return SEMICOLON;}}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{if(printTokens == 1) {printf("ARROW\n");} column += yyleng; if(printTokens == 0){return ARROW;}}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if(printTokens == 1) {printf("LSHIFT\n");} column += yyleng; if(printTokens == 0){return LSHIFT;}}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{if(printTokens == 1) {printf("RSHIFT\n");} column += yyleng; if(printTokens == 0){return RSHIFT;}}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if(printTokens == 1) {printf("XOR\n");} column += yyleng; if(printTokens == 0){return XOR;}}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{if(printTokens == 1) {printf("BOOL\n");} column += yyleng; if(printTokens == 0){return BOOL;}}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{if(printTokens == 1) {printf("CLASS\n");} column += yyleng; if(printTokens == 0){return CLASS;}}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "jucompiler.l"
{if(printTokens == 1) {printf("DOTLENGTH\n");} column += yyleng; if(printTokens == 0){return DOTLENGTH;}}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if(printTokens == 1) {printf("DOUBLE\n");} column += yyleng; if(printTokens == 0){return DOUBLE;}}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{if(printTokens == 1) {printf("ELSE\n");} column += yyleng; if(printTokens == 0){return ELSE;}}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{if(printTokens == 1) {printf("IF\n");} column += yyleng; if(printTokens == 0){return IF;}}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{if(printTokens == 1) {printf("INT\n");} column += yyleng; if(printTokens == 0){return INT;}}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{if(printTokens == 1) {printf("PRINT\n");} column += yyleng; if(printTokens == 0){return PRINT;}}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{if(printTokens == 1) {printf("PARSEINT\n");} column += yyleng; if(printTokens == 0){return PARSEINT;}}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if(printTokens == 1) {printf("PUBLIC\n");} column += yyleng; if(printTokens == 0){return PUBLIC;}}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{if(printTokens == 1) {printf("RETURN\n");} column += yyleng; if(printTokens == 0){return RETURN;}}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if(printTokens == 1) {printf("STATIC\n");} column += yyleng; if(printTokens == 0){return STATIC;}}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if(printTokens == 1) {printf("STRING\n");} column += yyleng; if(printTokens == 0){return STRING;}}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if(printTokens == 1) {printf("VOID\n");} column += yyleng; if(printTokens == 0){return VOID;}}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if(printTokens == 1) {printf("WHILE\n");} column += yyleng; if(printTokens == 0){return WHILE;}}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if(printTokens == 1) {printf("RESERVED(%s)\n",yytext);} column += yyleng; if(printTokens == 0){ yylval.string = strdup(yytext); return RESERVED;}}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if(printTokens == 1) {printf("ID(%s)\n",yytext);} column += yyleng; if(printTokens == 0){ yylval.string = strdup(yytext); return ID;}}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if(printTokens == 1) {printf("INTLIT(%s)\n",yytext);} column += yyleng; if(printTokens == 0){ yylval.string = strdup(yytext); return INTLIT;}}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if(printTokens == 1) {printf("REALLIT(%s)\n",yytext);} column += yyleng; if(printTokens == 0){ yylval.string = strdup(yytext); return REALLIT;}}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if(printTokens == 1) {printf("STRLIT(%s)\n",yytext);} column += yyleng; if(printTokens == 0){ yylval.string = strdup(yytext); return STRLIT;}}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{BEGIN COMMENT; column += yyleng;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{multiLineComment = 1;BEGIN COMMENT; commentTracker.line = line; commentTracker.column = column; column += yyleng;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if(multiLineComment == 1){multiLineComment = 0; BEGIN 0;} column = 1;}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if(multiLineComment == 0){BEGIN 0;} line++; column = 1;} //apanha comentario simples
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 98 "jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n", commentTracker.line, commentTracker.column); yyterminate();}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{column += yyleng; stringTracker.line = line; stringTracker.column = (int)(column-yyleng); BEGIN STRINGSTATE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{BEGIN 0; column += yyleng;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 106 "jucompiler.l"
{BEGIN 0; column += yyleng; printf("Line %d, col %d: invalid escape sequence (\\)\n", line, (int)(column-yyleng)); printf("Line %d, col %d: unterminated string literal\n", stringTracker.line, stringTracker.column); column = 1; line++;}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 107 "jucompiler.l"
{BEGIN 0; printf("Line %d, col %d: unterminated string literal\n", stringTracker.line, stringTracker.column) ; column = 1; line++;}
	YY_BREAK
case YY_STATE_EOF(STRINGSTATE):
#line 108 "jucompiler.l"
{column += yyleng; printf("Line %d, col %d: unterminated string literal\n", stringTracker.line, stringTracker.column); yyterminate();}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 109 "jucompiler.l"
{column += yyleng; printf("Line %d, col %d: invalid escape sequence (%s)\n", line, (int)(column-yyleng), yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 110 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{column += yyleng;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{column += 1;}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 116 "jucompiler.l"
{line++; column = 1;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{column += yyleng; printf("Line %d, col %d: illegal character (%s)\n", line, (int)(column-yyleng), yytext);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 119 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1344 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 369 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 369 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 368);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 119 "jucompiler.l"

int main(int argc, char** argv)
{
    if(argc > 1){
        if (strcmp(argv[1],"-l") == 0 || strcmp(argv[1],"-e1") == 0){
            if(strcmp(argv[1], "-l") == 0){
                printTokens = 1;
            }
            yylex();
        }
        else if(strcmp(argv[1],"-e2") == 0){
			printTokens = 0;
			yyparse();
		}
        else if(strcmp(argv[1],"-t") == 0){
			printTokens = 0;
			yyparse();
			if(syntaxError == 0){
				printTree(tree, 0);
                free_tree(tree);
			}
		}
    }
    else if(argc == 1){
        printTokens = 0;
		yyparse();
    }
   
    return 0;
}

int yywrap()
{
    return 1;
}
